version: "3.9"
services:
  character-bot:
    container_name: character-bot
    image: braxton/character-bot:latest
    restart: unless-stopped
    environment:
      # Cohere
      COHERE_API_KEY: 
      # Discord
      DISCORD_GUILD_ID: 
      DISCORD_BOT_TOKEN: 
      # Logging
      LOG_LEVEL: INFO
      # Database
      DB_HOST: database
      DB_DATABASE: character-bot
      DB_USER: character-bot
      DB_PASSWORD: 
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - mariadb:database
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    volumes:
        - ./config/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: character-bot
        MYSQL_USER: character-bot
        MYSQL_PASSWORD: 
        MYSQL_ROOT_PASSWORD: 
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
      # test: "/usr/local/mysql/bin/mysql --user=foo --password=foo --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
